### ISSUE TITLE
How to update custom server certificate in MQTT Broker

### ISSUE THREAD

**Issue by kvishal2203** [eclipse-hono/hono#3210]
Hi Team,

I'm trying to add our custom CA certificate in MQTT broker to enable port 8883. Can you please help me with the procedure.

**Comment by sophokles73** [comment]
I am not sure what you are trying to do/achieve. First, there is no MQTT broker in Hono. Are you referring to the MQTT protocol adapter? If so, are you talking about adding a certificate to the adapter's trust store so that it can authenticate devices presenting a client certificate? Or do you want to configure the adapter to present a custom server certificate to clients/devices that want to open a connection to the TLS protected port (8883)?

**Comment by kvishal2203** [comment]
@sophokles73 Yes. Im referring to mqtt protocol adapter. I want to know that is there a possibilities to add a server certificate to enable mqtt tls(8883). Here, my ultimate goal is to enable 8883 port.

**Comment by sophokles73** [comment]
Sure, please refer to the [MQTT adapter admin guide](https://www.eclipse.org/hono/docs/admin-guide/mqtt-adapter-config/).

**Comment by kvishal2203** [comment]
I refer to this page but still i have aa doubt in enable. Is there any article or ticket related to this feature.

**Comment by sophokles73** [comment]
Assuming that you want to install using the Helm chart, you might find some inspiration in the chart's Readme: https://github.com/eclipse/packages/tree/master/charts/hono

**Comment by kvishal2203** [comment]
@sophokles73 Im using hono for the past one year with mqtt(1883). Now, trying to enable mqtts(8883) in mqtt protocol adapter so please help me on how to add custom server certificate.

**Comment by kvishal2203** [comment]
@sophokles73 Im trying to achieve this feature which is mentioned in this page [Hono Secure Communication](https://www.eclipse.org/hono/docs/admin-guide/secure_communication/)

**Devices connecting to a Protocol Adapter** - Devices use TLS to both authenticate the protocol adapter and to establish an encrypted channel that provides integrity and privacy when transmitting data. Note that the specifics of if and how TLS can be used with a particular protocol adapter is specific to the transport protocol the adapter uses for communicating with the devices.

**Comment by sophokles73** [comment]
@BobClaerhout maybe you can help out here?

**Comment by BobClaerhout** [comment]
I think you are mixing things up here. You have internal communication between the different microservices (which is documented on the page you referenced: [Hono Secure Communicatin](https://www.eclipse.org/hono/docs/admin-guide/secure_communication/)) This doesn't have anything to do with securing incoming traffic.  
@sophokles73  already pointed out the helm install, I think this is your way forward indeed. Have a look at [line 1046 in the values file](https://github.com/eclipse/packages/blob/288098b27e5ba496801f7da5f71a148a98ef086e/charts/hono/values.yaml#L1046). This is the configuration of the mqtt adapter in which you can configure [extra secrets](https://github.com/eclipse/packages/blob/288098b27e5ba496801f7da5f71a148a98ef086e/charts/hono/values.yaml#L1120) and [extra environment variables](https://github.com/eclipse/packages/blob/288098b27e5ba496801f7da5f71a148a98ef086e/charts/hono/values.yaml#L1129). On the MQTT adapter admin page in the [Secure Port Only](https://www.eclipse.org/hono/docs/admin-guide/mqtt-adapter-config/#secure-port-only) section you should be able to find what you are looking for.

**Comment by kvishal2203** [comment]
@BobClaerhout  @sophokles73 

I have deployed and enabled the secure port with the given configuration details and it was working fine. Now, I had a problem in enabling my wildcard domain certificate which I updated in truststore.jks but, the protocol wasn't in a ready state. Later, I found the article about SNI in [Hono Secure Communication](https://www.eclipse.org/hono/docs/admin-guide/secure_communication/), I'm trying to enable my hostname(data.vish.com) to enable the custom server certificate. Please guide me on SNI part to achieve my goal.

**Comment by kvishal2203** [comment]
![image](https://user-images.githubusercontent.com/97879832/165586305-0d388939-8e07-4836-a5f8-2afce766bacd.png)

**Comment by kvishal2203** [comment]
[39m[38;5;145m2022-04-27 17:34:48,882[39m[38;5;188m [39m[38;5;66mDEBUG[39m[38;5;188m [[39m[38;5;69morg.ecl.hon.cli.imp.HonoConnectionImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151mstarting attempt [#86] to connect to server [eclipse-hono-dispatch-router:5673, role: Command & Control][39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:48,882[39m[38;5;188m [39m[38;5;66mDEBUG[39m[38;5;188m [[39m[38;5;69morg.ecl.hon.con.imp.ConnectionFactoryImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151mOpenSSL [available: false, supports KeyManagerFactory: false][39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:48,882[39m[38;5;188m [39m[38;5;66mDEBUG[39m[38;5;188m [[39m[38;5;69morg.ecl.hon.con.imp.ConnectionFactoryImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151musing JDK's default SSL engine[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:48,882[39m[38;5;188m [39m[38;5;66mDEBUG[39m[38;5;188m [[39m[38;5;69morg.ecl.hon.con.imp.ConnectionFactoryImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151menabling secure protocol [TLSv1.2][39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:48,882[39m[38;5;188m [39m[38;5;66mDEBUG[39m[38;5;188m [[39m[38;5;69morg.ecl.hon.con.imp.ConnectionFactoryImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151menabling secure protocol [TLSv1.3][39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:48,882[39m[38;5;188m [39m[38;5;66mDEBUG[39m[38;5;188m [[39m[38;5;69morg.ecl.hon.con.imp.ConnectionFactoryImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151mconnecting to AMQP 1.0 container [amqps://eclipse-hono-dispatch-router:5673, role: Command & Control][39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:48,901[39m[38;5;188m [39m[38;5;66mDEBUG[39m[38;5;188m [[39m[38;5;69morg.ecl.hon.con.imp.ConnectionFactoryImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151mcan't connect to AMQP 1.0 container [amqps://eclipse-hono-dispatch-router:5673, role: Command & Control]: Failed to create SSL connection[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:48,901[39m[38;5;188m [39m[38;5;137mWARN [39m[38;5;188m [[39m[38;5;69morg.ecl.hon.cli.imp.HonoConnectionImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151mattempt [#86] to connect to server [eclipse-hono-dispatch-router:5673, role: Command & Control] failed[39m[38;5;203m: javax.net.ssl.SSLHandshakeException: Failed to create SSL connection
	at io.vertx.core.net.impl.ChannelProvider$1.userEventTriggered(ChannelProvider.java:129)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
	at io.netty.handler.ssl.SslUtils.handleHandshakeFailure(SslUtils.java:443)
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1882)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1066)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.channels.ClosedChannelException
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1063)
	... 15 more
[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:49,261[39m[38;5;188m [39m[38;5;66mDEBUG[39m[38;5;188m [[39m[38;5;69morg.ecl.hon.cli.imp.HonoConnectionImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151mstarting attempt [#103] to connect to server [eclipse-hono-dispatch-router:5673, role: Downstream][39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:49,261[39m[38;5;188m [39m[38;5;66mDEBUG[39m[38;5;188m [[39m[38;5;69morg.ecl.hon.con.imp.ConnectionFactoryImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151mOpenSSL [available: false, supports KeyManagerFactory: false][39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:49,261[39m[38;5;188m [39m[38;5;66mDEBUG[39m[38;5;188m [[39m[38;5;69morg.ecl.hon.con.imp.ConnectionFactoryImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151musing JDK's default SSL engine[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:49,261[39m[38;5;188m [39m[38;5;66mDEBUG[39m[38;5;188m [[39m[38;5;69morg.ecl.hon.con.imp.ConnectionFactoryImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151menabling secure protocol [TLSv1.2][39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:49,261[39m[38;5;188m [39m[38;5;66mDEBUG[39m[38;5;188m [[39m[38;5;69morg.ecl.hon.con.imp.ConnectionFactoryImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151menabling secure protocol [TLSv1.3][39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:49,261[39m[38;5;188m [39m[38;5;66mDEBUG[39m[38;5;188m [[39m[38;5;69morg.ecl.hon.con.imp.ConnectionFactoryImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151mconnecting to AMQP 1.0 container [amqps://eclipse-hono-dispatch-router:5673, role: Downstream][39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:49,281[39m[38;5;188m [39m[38;5;66mDEBUG[39m[38;5;188m [[39m[38;5;69morg.ecl.hon.con.imp.ConnectionFactoryImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151mcan't connect to AMQP 1.0 container [amqps://eclipse-hono-dispatch-router:5673, role: Downstream]: Failed to create SSL connection[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-04-27 17:34:49,281[39m[38;5;188m [39m[38;5;137mWARN [39m[38;5;188m [[39m[38;5;69morg.ecl.hon.cli.imp.HonoConnectionImpl[39m[38;5;188m] ([39m[38;5;71mvert.x-eventloop-thread-1[39m[38;5;188m) [39m[38;5;151mattempt [#103] to connect to server [eclipse-hono-dispatch-router:5673, role: Downstream] failed[39m[38;5;203m: javax.net.ssl.SSLHandshakeException: Failed to create SSL connection
	at io.vertx.core.net.impl.ChannelProvider$1.userEventTriggered(ChannelProvider.java:129)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
	at io.netty.handler.ssl.SslUtils.handleHandshakeFailure(SslUtils.java:443)
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1882)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1066)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.channels.ClosedChannelException
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1063)
	... 15 more
[39m[38;5;227m

**Comment by kvishal2203** [comment]
Can you support me on this issue? @sophokles73

**Comment by sophokles73** [comment]
You will need to be more specific about what you are trying to do and what is working or not working as expected.
Please also make sure to [format log output as code](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).
