### ISSUE TITLE
Facing an issue while sending the one-way command using KafkaApplicationClientImpl through a java application

### ISSUE THREAD

**Issue by mhatrepratik11** [eclipse-hono/hono#3474]
**Hi Team**

**I am new to hono and I need your help in solving a issue.**
I am facing issue while sending one-way command through java application.

**NOTE: I am able to send one-way and request-response command both from CLI to the device and device (written in python) is able to receive the command and send the response as well.**

I am trying to send one way command using KafkaApplicationClientImpl. Please refer below code.

```
package com.hono.test.java.hono.controller;

import io.vertx.core.Vertx;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.json.JsonObject;
import java.time.Instant;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.hono.application.client.ApplicationClient;
import org.eclipse.hono.application.client.MessageContext;
import org.eclipse.hono.application.client.TimeUntilDisconnectNotification;
import org.eclipse.hono.application.client.kafka.impl.KafkaApplicationClientImpl;
import org.eclipse.hono.client.ServiceInvocationException;
import org.eclipse.hono.client.kafka.CommonKafkaClientConfigProperties;
import org.eclipse.hono.client.kafka.consumer.MessagingKafkaConsumerConfigProperties;
import org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory;
import org.eclipse.hono.client.kafka.producer.KafkaProducerFactory;
import org.eclipse.hono.client.kafka.producer.MessagingKafkaProducerConfigProperties;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class TestController {

  private static final Logger LOG = LoggerFactory.getLogger(TestController.class);
  private static final String KAFKA_CONSUMER_GROUP_ID = "hono-example-application";
  private static final String COMMAND_SEND_LIFECYCLE_INFO = "sendLifecycleInfo";
  private final Vertx vertx = Vertx.vertx();
  private final ApplicationClient<? extends MessageContext> client;
  public static final String tenantId = "327cb63f-b2b2-4df6-8879-b52a723a6b9d";
  public static final String deviceId = "2dea7245-f4bc-4bf8-a73a-29af037f6724";

  public TestController() {
    client = createKafkaApplicationClient();
  }

  private ApplicationClient<? extends MessageContext> createKafkaApplicationClient() {

    final Map<String, String> properties = new HashMap<>();
//    properties.put("bootstrap.servers", HonoExampleConstants.HONO_MESSAGING_HOST + ":" + port);
    properties.put("bootstrap.servers", "http://hono.eclipseprojects.io:9092");
    properties.put("reconnect.backoff.max.ms", "2000000");

    // add the following lines with appropriate values to enable TLS
    // properties.put("ssl.truststore.location", "/path/to/file");
    // properties.put("ssl.truststore.password", "secret");

    final CommonKafkaClientConfigProperties commonClientConfig = new CommonKafkaClientConfigProperties();
    commonClientConfig.setCommonClientConfig(properties);

    final MessagingKafkaConsumerConfigProperties consumerConfig = new MessagingKafkaConsumerConfigProperties();
    consumerConfig.setCommonClientConfig(commonClientConfig);
    consumerConfig.setConsumerConfig(Map.of("group.id", KAFKA_CONSUMER_GROUP_ID));

    final MessagingKafkaProducerConfigProperties producerConfig = new MessagingKafkaProducerConfigProperties();
    producerConfig.setCommonClientConfig(commonClientConfig);

    final KafkaProducerFactory<String, Buffer> producerFactory = CachingKafkaProducerFactory.sharedFactory(vertx);
    return new KafkaApplicationClientImpl(vertx, consumerConfig, producerFactory, producerConfig);
  }

  private static Buffer buildOneWayCommandPayload() {
    final JsonObject jsonCmd = new JsonObject().put("info", "app restarted.");
    return Buffer.buffer(jsonCmd.encodePrettily());
  }

  @GetMapping("sendCommand")
  public String sendCommand() {
    client.start();

    final Integer ttd = 60;
    final Instant creationTime = Instant.now();

    final Buffer commandBuffer = buildOneWayCommandPayload();
    final TimeUntilDisconnectNotification ttdNotification =
      new TimeUntilDisconnectNotification(tenantId, deviceId, ttd, creationTime);

    LOG.error("Sending one-way command [{}] to [{}].", COMMAND_SEND_LIFECYCLE_INFO, ttdNotification.getTenantAndDeviceId());

    client.sendOneWayCommand(tenantId, deviceId, COMMAND_SEND_LIFECYCLE_INFO, commandBuffer)
      .onSuccess(statusResult -> {
          LOG.error("Successfully sent one-way command payload: [{}] and received status [{}].",
            commandBuffer, statusResult);
      })
      .onFailure(t -> {
        if (t instanceof ServiceInvocationException) {
          final int errorCode = ((ServiceInvocationException) t).getErrorCode();
          LOG.error("One-way command was replied with error code [{}].", errorCode );
          LOG.error("One-way command was replied with message [{}].", t.getMessage());
          LOG.error("One-way command was replied with cause = " + t.getCause());
          t.printStackTrace();
        } else {
          LOG.error("Could not send one-way command : {}.", t.getMessage());
        }
      });

    return "Command successfully sent.";
  }
}
```

**NOTE. I am referring to [HonoExampleApplicationBase](https://github.com/eclipse-hono/hono/blob/master/examples/hono-client-examples/src/main/java/org/eclipse/hono/vertx/example/base/HonoExampleApplicationBase.java) this class in example package.**

**I am doing everything similar as given in <HonoExampleApplicationBase> this class.**

**The only change I have done in the above code is below.**
**I am using** 
bootstrap.servers = http://hono.eclipseprojects.io:9092
**Even I have tried with** 
bootstrap.servers = http://hono.eclipseprojects.io
bootstrap.servers = http://hono.eclipseprojects.io:9094

**Instead of** 
bootstrap.servers = http://127.0.0.1:9092/

**I am always getting error when tried to sending the one-way command.**

**Please refer error logs below.**

```
2023-03-10 00:10:37.837  INFO 66959 --- [nio-8087-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-03-10 00:10:37.837  INFO 66959 --- [nio-8087-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-03-10 00:10:37.845  INFO 66959 --- [nio-8087-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 8 ms
2023-03-10 00:10:37.968  INFO 66959 --- [nio-8087-exec-1] o.a.k.clients.producer.ProducerConfig    : ProducerConfig values: 
	acks = -1
	batch.size = 16384
	bootstrap.servers = [http://hono.eclipseprojects.io:9092]
	buffer.memory = 33554432
	client.dns.lookup = use_all_dns_ips
	client.id = command-sender-7ed7793e-c54a-4890-a9c7-61431356da07
	compression.type = none
	connections.max.idle.ms = 540000
	delivery.timeout.ms = 2500
	enable.idempotence = true
	interceptor.classes = []
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	linger.ms = 0
	max.block.ms = 500
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metadata.max.idle.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 2000000
	reconnect.backoff.ms = 50
	request.timeout.ms = 750
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.connect.timeout.ms = null
	sasl.login.read.timeout.ms = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.login.retry.backoff.max.ms = 10000
	sasl.login.retry.backoff.ms = 100
	sasl.mechanism = GSSAPI
	sasl.oauthbearer.clock.skew.seconds = 30
	sasl.oauthbearer.expected.audience = null
	sasl.oauthbearer.expected.issuer = null
	sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
	sasl.oauthbearer.jwks.endpoint.url = null
	sasl.oauthbearer.scope.claim.name = scope
	sasl.oauthbearer.sub.claim.name = sub
	sasl.oauthbearer.token.endpoint.url = null
	security.protocol = PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.timeout.ms = 60000
	transactional.id = null
	value.serializer = class io.vertx.kafka.client.serialization.BufferSerializer

2023-03-10 00:10:37.994  INFO 66959 --- [nio-8087-exec-1] o.a.k.clients.producer.KafkaProducer     : [Producer clientId=command-sender-7ed7793e-c54a-4890-a9c7-61431356da07] Instantiated an idempotent producer.
2023-03-10 00:10:38.070  INFO 66959 --- [nio-8087-exec-1] o.a.kafka.common.utils.AppInfoParser     : Kafka version: 3.1.1
2023-03-10 00:10:38.070  INFO 66959 --- [nio-8087-exec-1] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId: 97671528ba54a138
2023-03-10 00:10:38.070  INFO 66959 --- [nio-8087-exec-1] o.a.kafka.common.utils.AppInfoParser     : Kafka startTimeMs: 1678387238060
2023-03-10 00:10:38.156 ERROR 66959 --- [nio-8087-exec-1] c.h.t.j.hono.controller.TestController   : Sending one-way command [sendLifecycleInfo] to [327cb63f-b2b2-4df6-8879-b52a723a6b9d/2dea7245-f4bc-4bf8-a73a-29af037f6724].
2023-03-10 00:10:38.736 ERROR 66959 --- [ntloop-thread-0] c.h.t.j.hono.controller.TestController   : One-way command was replied with error code [503].
2023-03-10 00:10:38.737 ERROR 66959 --- [ntloop-thread-0] c.h.t.j.hono.controller.TestController   : One-way command was replied with message [Error Code: 503].
2023-03-10 00:10:38.737 ERROR 66959 --- [ntloop-thread-0] c.h.t.j.hono.controller.TestController   : One-way command was replied with cause = org.apache.kafka.common.errors.TimeoutException: Topic hono.command.327cb63f-b2b2-4df6-8879-b52a723a6b9d not present in metadata after 500 ms.
2023-03-10 00:10:38.742 ERROR 66959 --- [ntloop-thread-0] o.e.h.c.k.p.CachingKafkaProducerFactory  : producer error occurred [clientId: command-sender-7ed7793e-c54a-4890-a9c7-61431356da07]

org.apache.kafka.common.errors.TimeoutException: Topic hono.command.327cb63f-b2b2-4df6-8879-b52a723a6b9d not present in metadata after 500 ms.

org.eclipse.hono.client.ServerErrorException: Error Code: 503
	at org.eclipse.hono.client.kafka.producer.AbstractKafkaBasedMessageSender.lambda$sendAndWaitForOutcome$3(AbstractKafkaBasedMessageSender.java:273)
	at io.vertx.core.impl.future.Otherwise.onFailure(Otherwise.java:35)
	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onFailure(FutureImpl.java:268)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.Mapping.onFailure(Mapping.java:45)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.common.errors.TimeoutException: Topic hono.command.327cb63f-b2b2-4df6-8879-b52a723a6b9d not present in metadata after 500 ms.
2023-03-10 00:10:38.886  INFO 66959 --- [c7-61431356da07] org.apache.kafka.clients.NetworkClient   : [Producer clientId=command-sender-7ed7793e-c54a-4890-a9c7-61431356da07] Node -1 disconnected.
2023-03-10 00:10:38.888  WARN 66959 --- [c7-61431356da07] org.apache.kafka.clients.NetworkClient   : [Producer clientId=command-sender-7ed7793e-c54a-4890-a9c7-61431356da07] Connection to node -1 (hono.eclipseprojects.io/104.196.140.16:9092) could not be established. Broker may not be available.
2023-03-10 00:10:38.889  WARN 66959 --- [c7-61431356da07] org.apache.kafka.clients.NetworkClient   : [Producer clientId=command-sender-7ed7793e-c54a-4890-a9c7-61431356da07] Bootstrap broker hono.eclipseprojects.io:9092 (id: -1 rack: null) disconnected
```

**Please help. Thanks.**

**Comment by mhatrepratik11** [comment]
Closing this issue as I got it resolved. Was doing something wrong with sandbox-hostname.
