### ISSUE TITLE
Hono sandbox Certificate issue

### ISSUE THREAD

**Issue by NagaRajeshK** [eclipse-hono/hono#3493]
Hi Team,
I am following the getting started article and trying to communicate with Hono sandbox instance. I am not run hono-cli-2.3.0 and mosquitto_pub.exe due to certificate issue. I think its unable to find ca-certificates.crt in my windows machine. Could you please help me? How can I get this certificate make it work in my windows PC.
![image](https://github.com/eclipse-hono/hono/assets/5278392/c9ab1bbb-3480-46ec-ba66-97eddf5b0328)

Thanks,
Rajesh.

**Comment by NagaRajeshK** [comment]
Hi @sophokles73 . Sorry for the screenshots. 
I was running the following commands in GIT bash of my windows machine.  I am betting the below error. The issue could be hono client is looking for a certificates but they are not available in windows machine. How to get these certificates?

`source hono.env
 java -jar hono-cli-2.2.0-exec.jar app ${APP_OPTIONS} consume --tenant ${MY_TENANT}
`
**Getting the following error: **
`Connecting to Kafka based messaging infrastructure [hono.eclipseprojects.io:9094]
2023-05-31 11:11:29,032 ERROR [org.apa.kaf.com.sec.ssl.DefaultSslEngineFactory] (main) Modification time of key store could not be obtained: C:/Users/kotapn2/AppData/Local/Programs/Git/etc/ssl/certs/ca-certificates.crt: java.nio.file.NoSuchFileException: C:\Users\kotapn2\AppData\Local\Programs\Git\etc\ssl\certs\ca-certificates.crt
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.nio.file.Files.getLastModifiedTime(Files.java:2402)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.lastModifiedMs(DefaultSslEngineFactory.java:383)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.<init>(DefaultSslEngineFactory.java:348)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedPemStore.<init>(DefaultSslEngineFactory.java:405)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.createTruststore(DefaultSslEngineFactory.java:318)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.configure(DefaultSslEngineFactory.java:168)
        at org.apache.kafka.common.security.ssl.SslFactory.instantiateSslEngineFactory(SslFactory.java:140)
        at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:97)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:180)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
        at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:484)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:428)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:289)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:272)
        at io.vertx.kafka.client.producer.KafkaWriteStream.create(KafkaWriteStream.java:103)
        at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.lambda$createShared$1(KafkaProducerImpl.java:57)
        at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.lambda$createShared$9(KafkaProducerImpl.java:104)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.createShared(KafkaProducerImpl.java:103)
        at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.createShared(KafkaProducerImpl.java:57)
        at io.vertx.kafka.client.producer.KafkaProducer.createShared(KafkaProducer.java:68)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.lambda$sharedFactory$0(CachingKafkaProducerFactory.java:97)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.lambda$getOrCreateProducer$2(CachingKafkaProducerFactory.java:172)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.getOrCreateProducer(CachingKafkaProducerFactory.java:169)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.lambda$getOrCreateProducerWithRetries$3(CachingKafkaProducerFactory.java:197)
        at org.eclipse.hono.client.kafka.KafkaClientFactory.createClientWithRetries(KafkaClientFactory.java:200)
        at org.eclipse.hono.client.kafka.KafkaClientFactory.createClientWithRetries(KafkaClientFactory.java:136)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.getOrCreateProducerWithRetries(CachingKafkaProducerFactory.java:196)
        at org.eclipse.hono.client.kafka.producer.AbstractKafkaBasedMessageSender.start(AbstractKafkaBasedMessageSender.java:164)
        at org.eclipse.hono.cli.app.NorthBoundApis.startClientAndWaitForReadiness(NorthBoundApis.java:232)
        at org.eclipse.hono.cli.app.NorthBoundApis.createKafkaClient(NorthBoundApis.java:185)
        at org.eclipse.hono.cli.app.NorthBoundApis.getApplicationClient(NorthBoundApis.java:250)
        at org.eclipse.hono.cli.app.TelemetryAndEvent.call(TelemetryAndEvent.java:156)
        at org.eclipse.hono.cli.app.TelemetryAndEvent.call(TelemetryAndEvent.java:48)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:131)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:43)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

2023-05-31 11:11:29,040 WARN  [org.ecl.hon.cli.kaf.KafkaClientFactory] (main) failed to create client due to terminal error (won't retry): org.apache.kafka.common.KafkaException: Failed to construct kafka producer
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:439)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:289)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:272)
        at io.vertx.kafka.client.producer.KafkaWriteStream.create(KafkaWriteStream.java:103)
        at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.lambda$createShared$1(KafkaProducerImpl.java:57)
        at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.lambda$createShared$9(KafkaProducerImpl.java:104)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.createShared(KafkaProducerImpl.java:103)
        at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.createShared(KafkaProducerImpl.java:57)
        at io.vertx.kafka.client.producer.KafkaProducer.createShared(KafkaProducer.java:68)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.lambda$sharedFactory$0(CachingKafkaProducerFactory.java:97)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.lambda$getOrCreateProducer$2(CachingKafkaProducerFactory.java:172)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.getOrCreateProducer(CachingKafkaProducerFactory.java:169)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.lambda$getOrCreateProducerWithRetries$3(CachingKafkaProducerFactory.java:197)
        at org.eclipse.hono.client.kafka.KafkaClientFactory.createClientWithRetries(KafkaClientFactory.java:200)
        at org.eclipse.hono.client.kafka.KafkaClientFactory.createClientWithRetries(KafkaClientFactory.java:136)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.getOrCreateProducerWithRetries(CachingKafkaProducerFactory.java:196)
        at org.eclipse.hono.client.kafka.producer.AbstractKafkaBasedMessageSender.start(AbstractKafkaBasedMessageSender.java:164)
        at org.eclipse.hono.cli.app.NorthBoundApis.startClientAndWaitForReadiness(NorthBoundApis.java:232)
        at org.eclipse.hono.cli.app.NorthBoundApis.createKafkaClient(NorthBoundApis.java:185)
        at org.eclipse.hono.cli.app.NorthBoundApis.getApplicationClient(NorthBoundApis.java:250)
        at org.eclipse.hono.cli.app.TelemetryAndEvent.call(TelemetryAndEvent.java:156)
        at org.eclipse.hono.cli.app.TelemetryAndEvent.call(TelemetryAndEvent.java:48)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:131)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:43)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.errors.InvalidConfigurationException: Failed to load PEM SSL keystore C:/Users/kotapn2/AppData/Local/Programs/Git/etc/ssl/certs/ca-certificates.crt
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
        at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:484)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:428)
        ... 37 more
Caused by: org.apache.kafka.common.errors.InvalidConfigurationException: Failed to load PEM SSL keystore C:/Users/kotapn2/AppData/Local/Programs/Git/etc/ssl/certs/ca-certificates.crt
Caused by: java.io.IOException: Unable to read file C:/Users/kotapn2/AppData/Local/Programs/Git/etc/ssl/certs/ca-certificates.crt
        at org.apache.kafka.common.utils.Utils.readFileAsString(Utils.java:739)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedPemStore.load(DefaultSslEngineFactory.java:411)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.<init>(DefaultSslEngineFactory.java:349)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedPemStore.<init>(DefaultSslEngineFactory.java:405)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.createTruststore(DefaultSslEngineFactory.java:318)
        at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.configure(DefaultSslEngineFactory.java:168)
        at org.apache.kafka.common.security.ssl.SslFactory.instantiateSslEngineFactory(SslFactory.java:140)
        at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:97)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:180)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
        at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:484)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:428)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:289)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:272)
        at io.vertx.kafka.client.producer.KafkaWriteStream.create(KafkaWriteStream.java:103)
        at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.lambda$createShared$1(KafkaProducerImpl.java:57)
        at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.lambda$createShared$9(KafkaProducerImpl.java:104)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.createShared(KafkaProducerImpl.java:103)
        at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.createShared(KafkaProducerImpl.java:57)
        at io.vertx.kafka.client.producer.KafkaProducer.createShared(KafkaProducer.java:68)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.lambda$sharedFactory$0(CachingKafkaProducerFactory.java:97)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.lambda$getOrCreateProducer$2(CachingKafkaProducerFactory.java:172)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.getOrCreateProducer(CachingKafkaProducerFactory.java:169)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.lambda$getOrCreateProducerWithRetries$3(CachingKafkaProducerFactory.java:197)
        at org.eclipse.hono.client.kafka.KafkaClientFactory.createClientWithRetries(KafkaClientFactory.java:200)
        at org.eclipse.hono.client.kafka.KafkaClientFactory.createClientWithRetries(KafkaClientFactory.java:136)
        at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.getOrCreateProducerWithRetries(CachingKafkaProducerFactory.java:196)
        at org.eclipse.hono.client.kafka.producer.AbstractKafkaBasedMessageSender.start(AbstractKafkaBasedMessageSender.java:164)
        at org.eclipse.hono.cli.app.NorthBoundApis.startClientAndWaitForReadiness(NorthBoundApis.java:232)
        at org.eclipse.hono.cli.app.NorthBoundApis.createKafkaClient(NorthBoundApis.java:185)
        at org.eclipse.hono.cli.app.NorthBoundApis.getApplicationClient(NorthBoundApis.java:250)
        at org.eclipse.hono.cli.app.TelemetryAndEvent.call(TelemetryAndEvent.java:156)
        at org.eclipse.hono.cli.app.TelemetryAndEvent.call(TelemetryAndEvent.java:48)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:131)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:43)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.nio.file.NoSuchFileException: C:\Users\kotapn2\AppData\Local\Programs\Git\etc\ssl\certs\ca-certificates.crt
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
        at org.apache.kafka.common.utils.Utils.readFileAsString(Utils.java:736)
`

**Comment by sophokles73** [comment]
You can download the CA certificates from [Let's Encrypt](https://letsencrypt.org/certificates/).
You can download the self-signed ISRG Root X1 PEM file and move it to the location that the Hono CLI expects it to find at, i.e. `C:/Users/kotapn2/AppData/Local/Programs/Git/etc/ssl/certs/ca-certificates.crt`
