### ISSUE TITLE
External Kafka config not working.

### ISSUE THREAD

**Issue by snowwolf007cn** [eclipse-hono/hono#3522]
I create my own value file below:

```yaml
adapters:
  kafkaMessagingSpec:
    commonClientConfig:
      bootstrap.servers: "host.minikube.internal:29092"

deviceRegistryExample:
  addExampleData: false

kafkaMessagingClusterExample:
  enabled: false
```

and install hono in my minikube:
```shell
helm install eclipse-hono eclipse-iot/hono -n hono -f private-deploy-values.yaml
```

after a few minutes, I checked the installation using:
```shell
kubectl get pods -n hono
```

and it said:
```
eclipse-hono-adapter-amqp-5856984df8-n4ng8             0/1     Running   0          6m19s
eclipse-hono-adapter-http-c94556fcf-vnlc2              0/1     Running   0          6m19s
eclipse-hono-adapter-mqtt-559448fcfd-g5sd9             0/1     Running   0          6m19s
eclipse-hono-service-auth-5c848487d6-6q799             1/1     Running   0          6m19s
eclipse-hono-service-command-router-5dd88d7df6-2b8wb   0/1     Running   0          6m19s
eclipse-hono-service-device-registry-0                 1/1     Running   0          6m19s
```

I checked log of pod command-router, and here what I read:
```log
2023-07-28 21:32:11,339 WARN  [org.apa.kaf.cli.NetworkClient] (vert.x-kafka-consumer-thread-0) [Consumer clientId=notification-8ce4dd5e-e64f-4601-ae51-d62bcf7942ec, groupId=4cb32091-77f8-4be2-8a81-c95fa37211de] Error connecting to node 2260681b4253:9092 (id: 1 rack: null): java.net.UnknownHostException: 2260681b4253: Name or service not known
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
	at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:110)
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:510)
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
	at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:173)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:990)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:513)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:270)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:265)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:492)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:524)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1276)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1220)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$pollRecords$6(KafkaReadStreamImpl.java:155)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

How to make this work?

**Comment by snowwolf007cn** [comment]
I just found there is a problem with my Kafka docker container.
