### ISSUE TITLE
CLI: NullPointerException in amqp-device or command mode

### ISSUE THREAD

**Issue by calohmn** [eclipse-hono/hono#3576]
When starting the Hono CLI based on current Hono master, there is an NPE when using the `amqp-device` mode or the mode to send commands.
E.g.
```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at org.jline.console.impl.Builtins.<init>(Builtins.java:83)
	at org.jline.console.impl.Builtins.<init>(Builtins.java:74)
	at org.eclipse.hono.cli.adapter.amqp.AmqpAdapter.readAndExecuteCommands(AmqpAdapter.java:269)
	at org.eclipse.hono.cli.adapter.amqp.AmqpAdapter.call(AmqpAdapter.java:403)
	at org.eclipse.hono.cli.adapter.amqp.AmqpAdapter.call(AmqpAdapter.java:78)
```
(line number in `AmqpAdapter.java` refers to my locally changed file)

The issue is that the `org.jline.console.impl.Builtins` class now requires a non-null `configpath` parameter value.
This has been introduced in JLine 3.22 (see [here](https://github.com/jline/jline3/commit/9706eadf152981ca9f5dfaac87aff2166e88e080)). In current Hono master, JLine 3.23 is used.

In Hono 2.4, JLine 3.21 is used, so there's probably no issue there.

**Comment by sophokles73** [comment]
Thanks for spotting :+1:
